// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts


### Get a single contact by ID
GET http://localhost:8080/contacts/68b5b7cb67003f60aa3d8049


### Create a new contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jeff",
    "lastName": "Jefferson",
    "email": "jeff.jefferson@gmail.com",
    "favoriteColor": "blue",
    "birthday": "1980-08-01"
}


### Update an existing contact by ID
PUT http://localhost:8080/contacts/68c33abfdbee747214e24ebd HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jeff",
    "lastName": "Jefferson",
    "email": "jeff-jefferson@gmail.com",
    "favoriteColor": "blue",
    "birthday": "1980-08-02"
}


### Delete a contact by ID
DELETE http://localhost:8080/contacts/68c2d5388409bf4a40ca821d HTTP/1.1